### ISSUE TITLE
This is a query regarding Hypergraph

### ISSUE THREAD

**Issue by TejasAnvekar** [MegaYEye/Triangle-Net#1]
Hello sir,

I had a query regarding, what part of your code contributes for hypergraph construction and convolution, which is mentioned in paper.

It would be really great full if you could provide more insights

Thanks and regards.

**Comment by MegaYEye** [comment]
The concept is taken from the paper "Feng, Yifan, et al. "Hypergraph neural networks." Proceedings of the AAAI conference on artificial intelligence. Vol. 33. No. 01. 2019." The term is used because the random triangle connection shares the same idea. In fact, we attempted to explain it more straightforwardly through geometric shapes, but it was not appreciated by reviewers previously due to a lack of mathematical intuition.

The term hyperedge means that it can involve three points connecting to each other. For example, when adding distance/angular values relative to the centroid point, it has a Y-shaped "edge". However, the centroid point itself is not part of the point cloud (and does not belong to set V).

The convolution is used to aggregate multiple features described above. Many point cloud models share a similar concept as a graph neural network, such as DGCNN and PointNet. We aggregate multiple such edge features using a max function. It is a convolution on multiple hypergraph features, rather than inside a single triangle graph.

In our code, the construction is the part that calculates distances and angles. The convolution is the max aggregation used to obtain latent features from all hyperedge features.
